-- Rizik Empire Sub-system DB Migration

-- 1. B2B Organizations (Mosques, Corporate Entities, Wholesalers)
CREATE TABLE IF NOT EXISTS public.b2b_organizations (
    org_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('MOSQUE', 'AGRO_CORP', 'WHOLESALER', 'EVENT_PLANNER')),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    registration_number VARCHAR(100),
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Empire Products Master Catalog
CREATE TABLE IF NOT EXISTS public.empire_products (
    product_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL CHECK (category IN ('ECO_MAT', 'BIO_SHIELD', 'OTHER')),
    description TEXT,
    base_price_bdt DECIMAL(12, 2) NOT NULL,
    minimum_order_quantity INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Bulk Orders generated by B2B Organizations
CREATE TABLE IF NOT EXISTS public.bulk_orders (
    order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID REFERENCES public.b2b_organizations(org_id) ON DELETE CASCADE,
    manager_id UUID NOT NULL, -- References auth.users (the specific user managing the order)
    status VARCHAR(50) NOT NULL CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'MANUFACTURING', 'QUALITY_CHECK', 'READY_TO_SHIP', 'DELIVERED', 'CANCELLED')),
    total_amount_bdt DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    delivery_address TEXT,
    special_instructions TEXT, -- For custom prints, glow ink requests, etc.
    expected_delivery_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Order Items (Bridge between Orders and Products)
CREATE TABLE IF NOT EXISTS public.bulk_order_items (
    item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID REFERENCES public.bulk_orders(order_id) ON DELETE CASCADE,
    product_id UUID REFERENCES public.empire_products(product_id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_bdt DECIMAL(12, 2) NOT NULL,
    subtotal_bdt DECIMAL(15, 2) GENERATED ALWAYS AS (quantity * unit_price_bdt) STORED
);

-- 5. Production Batches (To track manufacturing of Active Packaging and Mats)
CREATE TABLE IF NOT EXISTS public.production_batches (
    batch_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID REFERENCES public.empire_products(product_id) ON DELETE CASCADE,
    order_id UUID REFERENCES public.bulk_orders(order_id) ON DELETE SET NULL, -- Null if producing for stock
    batch_status VARCHAR(50) NOT NULL CHECK (batch_status IN ('QUEUED', 'IN_PROGRESS', 'TESTING', 'COMPLETED')),
    quantity_produced INTEGER NOT NULL DEFAULT 0,
    quality_score DECIMAL(5, 2), -- 0.00 to 100.00
    production_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Initial Seed Data (Core Empire Products)
INSERT INTO public.empire_products (sku, name, category, description, base_price_bdt, minimum_order_quantity)
VALUES 
('MAT-GLOW-01', 'Barishal Eco Pray Mat - Glow Series', 'ECO_MAT', '100% Biodegradable, Night-Glow ink, Taraweeh optimized.', 150.00, 100),
('MAT-SCENT-01', 'Barishal Eco Pray Mat - Oud Infused', 'ECO_MAT', '100% Biodegradable, Oud Scent bonded fabric.', 120.00, 100),
('BIO-VEG-01', 'Bio-Shield Matrix - Vegetable Membrane', 'BIO_SHIELD', '30 GSM + 20 Micron LDPE. 15-day shelf life for perishables.', 25.00, 1000),
('BIO-RETORT-V1', 'Bio-Shield Retort Pouch (1yr)', 'BIO_SHIELD', '80 GSM + 50 Micron LDPE. God Mode preservation (121C).', 85.00, 500)
ON CONFLICT (sku) DO NOTHING;

-- RLS Policies placeholder: Admin override only for now.
-- In production, policies should restrict orgs to see only their own bulk_orders.
