import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:rizik_v4/data/models/vibe_video.dart';

/// Repository to fetch generated marketing videos from Supabase
/// Videos are generated by the pipeline and auto-pushed to this table
class GeneratedVideoRepository {
  final SupabaseClient _client;
  
  GeneratedVideoRepository() : _client = Supabase.instance.client;
  
  /// Fetch all generated videos ordered by creation date (newest first)
  Future<List<VibeVideo>> getGeneratedVideos({int limit = 20}) async {
    try {
      final response = await _client
          .from('generated_videos')
          .select()
          .order('created_at', ascending: false)
          .limit(limit);
      
      return (response as List).map((json) => _convertToVibeVideo(json)).toList();
    } catch (e) {
      print('Error fetching generated videos: $e');
      return [];
    }
  }
  
  /// Convert Supabase JSON to VibeVideo model
  VibeVideo _convertToVibeVideo(Map<String, dynamic> json) {
    return VibeVideo(
      id: json['id'] ?? 'gen_${DateTime.now().millisecondsSinceEpoch}',
      creatorId: 'rizik_ai',
      creatorName: 'Rizik AI',
      creatorAvatar: 'https://pub-b00b750231d04ca29f9683a360790349.r2.dev/rizik-logo.png',
      creatorTrustScore: 5.0,
      creatorAuraLevel: 99,
      videoUrl: json['video_url'] ?? '',
      thumbnailUrl: '', // Video player will generate thumbnail
      caption: '${json['product_name'] ?? 'Product'} - AI Generated Ad 🚀',
      hashtags: ['#RizikAI', '#${json['product_type'] ?? 'Product'}', '#Trending'],
      durationSeconds: 7, // Our videos are 7 seconds
      linkedFoodId: null,
      linkedFoodName: json['product_name'],
      linkedFoodPrice: null,
      linkedPartnerId: null,
      linkedPartnerName: 'Rizik Marketing',
      viewCount: 0,
      likeCount: 0,
      shareCount: 0,
      commentCount: 0,
      orderCount: 0,
      isVerified: true,
      isViral: false,
      createdAt: DateTime.tryParse(json['created_at'] ?? '') ?? DateTime.now(),
      totalViewEarnings: 0,
      totalCommissionEarnings: 0,
    );
  }
  
  /// Stream of videos for real-time updates
  Stream<List<VibeVideo>> watchGeneratedVideos() {
    return _client
        .from('generated_videos')
        .stream(primaryKey: ['id'])
        .order('created_at', ascending: false)
        .limit(20)
        .map((data) => data.map((json) => _convertToVibeVideo(json)).toList());
  }
}
