name = "rizik-backend"
main = "backend/src/index.ts"
compatibility_date = "2024-04-01"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" },
  { name = "VOICE_AGENT", class_name = "VoiceAgent" }
]

[ai]
binding = "AI"

[[migrations]]
tag = "v6"
new_sqlite_classes = ["ChatRoom", "VoiceAgent"]

[vars]
ENVIRONMENT = "production"
CALLS_APP_ID = "1e976218463f682ebf0f56c0667a5482"
LIVEKIT_URL = "wss://rizik-ai-femz194x.livekit.cloud"
LIVEKIT_API_KEY = "APImSG78KpGRGdm"
LIVEKIT_API_SECRET = "MdKvfAwLfivlzlQmgRfJ268XvW79vSyqidour2e1kQnC"

# R2 Buckets for Storage (Images, Proofs)
[[r2_buckets]]
binding = "RIZIK_STORAGE"
bucket_name = "rizik-storage-v1"
